### ISSUE TITLE
Request to Package and Publish on PyPI

### ISSUE THREAD

**Issue by Lucandia** [febos/SQUARNA#1]
Hello,

First of all, thank you for your work on this project. I find it extremely useful, I was looking forward to an RNA secondary structure prediction program in Python!

Would it be possible for this program to be packaged and made available on the PyPI (Python Package Index)? This would make it extremely easily accessible, so it can be installed and used via `pip`. I'm asking this because I'd like to import SQUARNA into Python scripts and insert it into my workflow!

Packaging and publishing on PyPI would involve:
1. Creating a `setup.py` or `pyproject.toml` file to define the package metadata.
2. Ensuring all dependencies are listed in the appropriate configuration file.
3. Registering on PyPI and uploading the package.

Here are some resources that might help with this process:
- [Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/)
- [PyPI User Guide](https://pypi.org/help/#user-guide)

I would be more than happy to help you!
Please let me know if there is anything specific you need help with or if there are any steps you would like me to take.
I could also fork the repository, package it and upload it to Pypi or submit a pull request.

Thank you for considering this request. Please let me know if there is any way I can help in this process.

Best regards,
   Luca Monari

**Comment by febos** [comment]
Hi Luca!
Thank you for your request!
Yes, I was going to make SQUARNA installable with pip sooner or later. Now I will do it sooner, hopefully tomorrow :)
I'll let you know if I need any help, thanks again!

Best regards,
Eugene Baulin

**Comment by febos** [comment]
Hi Luca!

Done!

You can now install SQUARNA with pip, import, and run as a Python function, see:
https://github.com/febos/SQUARNA/blob/main/demo.ipynb

Currently, the Predict function does the same thing as the command-line SQUARNA.
Please let us know if it suits you. 
Any other requests are welcome!

**Comment by Lucandia** [comment]
Thank you so much, I'll try it for sure!
